name: sound
version: 0.1.0
author: "bnspalding"
copyright: "Copyright (c) 2019 - 2020 Ben Spalding"
synopsis: "working with sounds: features, syllables, IPA, rhyme"
description: Please see the README on GitHub at <https://github.com/bnspalding/sound#readme>

dependencies:
  - base >= 4.9 && < 5
  - containers
  - text-replace >= 0.0.0.4
  - text

library:
  source-dirs: src

tests:
  Sound-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - sound
      - hspec

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
