name: sound
version: 0.0
author: "bnspalding"
copyright: "Copyright (c) 2019 Ben Spalding"
synopsis: "project description for sound"
#TODO: add synopsis for package
description: Please see the README on GitHub at <https://github.com/bnspalding/sound#readme>

dependencies:
  - base >= 4.9 && < 5
  - containers
  - text-replace >= 0.0.0.4

library:
  source-dirs: src

tests:
  Sound-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - Sound
      - hspec

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
